version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/elivision-ai-1-4e63af45bd31.json
      - GEMINI_MODEL=gemini-1.5-pro
      - CHROMA_PERSIST_DIRECTORY=/app/data/vector_db
      - MAX_CONTEXT_LENGTH=4000
      - SIMILARITY_THRESHOLD=0.7
      - MAX_RETRIEVED_DOCS=5
      - API_KEY_HEADER=X-API-Key
      - ALLOWED_ORIGINS=["http://localhost:3000"]
    volumes:
      - ./backend:/app
      - ./elivision-ai-1-4e63af45bd31.json:/app/credentials/elivision-ai-1-4e63af45bd31.json:ro
      - vector_data:/app/data/vector_db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add Redis for future conversation persistence
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped

volumes:
  vector_data:
    driver: local 